### PR TITLE
Fix models like phi-3 which have a mismatched tokenizer definition and model output tensor size

### PR DESCRIPTION
**Pull request by Harsha-Nori**
The Phi-3 Mini models (e.g. https://huggingface.co/microsoft/Phi-3-mini-4k-instruct) have a total tokenizer vocab size of 32011 (base 32000 plus 11 special tokens), but the model outputs logit vectors of size 32064 (for CUDA performance reasons maybe?). 

I _think_ models that use this trick will always have the "padded" model output at the end, which makes this PR a very clean and simple change to guarantee tokenizer <> model output consistency. This fix will NOT work if the padded outputs are either in the beginning or interspersed throughout the token vector, but I haven't seen a model do that yet. If models do start doing that, we'll need to make significantly heavier changes across the guidance codebase, as we currently heavily rely on the len(tokenizer) to be usable for iteration.

### CODE REVIEW

**Comment by Harsha-Nori** [comment]
Build failure seems to be unrelated to this change @riedgar-ms

**Comment by riedgar-ms** [comment]
Doesn't this need to be combined with the Phi3-enabling PR?

**Comment by Harsha-Nori** [comment]
> Doesn't this need to be combined with the Phi3-enabling PR?

Yes, oops, meant to merge that in. Just did.

**Review by riedgar-ms — APPROVED** [review]
Gates looking good so far....

**Comment by Harsha-Nori** [comment]
Build failures on Mac seem to be due to build machine size issues, not this change. I can run all tests on my Mac.

**Pull request merged**
