### PR TITLE
Update JSON API and example notebook

### PR DESCRIPTION
**Pull request by riedgar-ms**
Add the new JSON schema functionality to the example notebook for guaranteeing valid syntax. Also, rename the `json_schema` argument in the `guidance.json()` function to be just `schema`.

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks @riedgar-ms ! Looks great. The only change I would suggest is changing `from guidance.library import json as gen_json` to `from guidance import json as gen_json` since we expose all the library functions at the top level.

One other note unrelated to this PR, why do we have `json_schema` instead of `schema` for `json_schema=character_schema_obj`? It seems like it is obviously a json schema since we are generating json and `schema` matches other libraries like jsonschema

**Comment by riedgar-ms** [comment]
No particular reason on the argument naming, beyond "That's what came to mind first." I have updated (tag @hudson-ai  for info).

We probably should review the arguments across all public functions, and make sure we're consistent about which have to be named when present.

**Comment by hudson-ai** [comment]
Wonderful! Thank you @riedgar-ms for looping me in :)

May be a separate PR, but it may be worth adding some extra info around effective prompting (in `art_of_prompt_design`?). Note in particular that `quest_items` are now just `"."`...

E.g. **showing** the LM what schema it will use ahead of time and even adding `examples` to the schema, e.g. 
```json
{
    "type": "object",
    "properties": {
        "description" : { "type" : "string" },
        "name" : { "type" : "string" },
        "age" : { "type" : "integer" },
        "armour" : { "type" : "string", "enum" : ["leather", "chainmail", "plate"] },
        "weapon" : { "type" : "string", "enum" : ["sword", "axe", "mace", "spear", "bow", "crossbow"] },
        "class" : { "type" : "string" },
        "mantra" : { "type" : "string" },
        "strength" : { "type" : "integer" },
        "quest_items" : {
            "type" : "array",
            "items": { "type": "string" },
            "examples": ["Triforce", "Master Sword"],
        }
    }
}
```
I'd also put forward that generating JSON is a popular enough use-case that an example deserves to be in the `README`!

**Comment by riedgar-ms** [comment]
@hudson-ai Something like that would probably be good in expanded documentation (I have a few ideas for what to do with the notebooks, since the fact that they're not run regularly is a big problem).

@slundberg does this look better to you?

**Comment by riedgar-ms** [comment]
Ping @slundberg

**Comment by riedgar-ms** [comment]
@slundberg does this address your concerns?

**Comment by riedgar-ms** [comment]
@slundberg does this address your concerns?

**Comment by riedgar-ms** [comment]
@slundberg ?

**Comment by riedgar-ms** [comment]
Is the API now more in line with your preferences @slundberg ?

**Comment by Harsha-Nori** [comment]
API seems fine to me. Seems like a nice set of updates and examples - thanks! Merging.

**Pull request merged**
