### PR TITLE
[Bug] Pass-through kwargs in `TransformersTokenizer`

### LINKED ISSUE #909: trust_remote_code not honored
**The bug**
Passing `trust_remote_code=True` is not honored for every invocation of the model.

**To Reproduce**
```python
from guidance import models
lm = models.Transformers('openbmb/MiniCPM-Llama3-V-2_5', trust_remote_code=True)

print(lm + "what is love?")
```

See image attached
image

### PR DESCRIPTION
**Pull request by riedgar-ms**
If `TransformersModel` has `kwargs`, make sure that they reach the tokeniser.

Closes #909

### CODE REVIEW

**Comment by hudson-ai** [comment]
Just documenting an offline discussion with @riedgar-ms -- it's clearly not always safe to pass all kwargs to the tokenizer if they were intended to be passed to the model. Need to think a bit more about how to handle this ergonomically.

**Comment by riedgar-ms** [comment]
I think that the only safe way will be your suggestion of a `tokenizer_kwargs : Dict[str,Any]` argument. Not great, though

**Comment by hudson-ai** [comment]
@riedgar-ms I think I agree with @Harsha-Nori's [comment](https://github.com/guidance-ai/guidance/issues/909#issuecomment-2183388663). We do support directly passing a tokenizer, so maybe that's the right workaround if the user has a complex configuration. Special-casing `trust_remote_code` would at least fix this particular (and I expect more common) problem.

**Comment by riedgar-ms** [comment]
Going to be superseded after discussion

**Pull request closed without merging**
