### PR TITLE
Update guidance_acceleration.ipynb

### PR DESCRIPTION
**Pull request by ScottzCodez**
### I refactored this but it's my first time using github  -- can someone put quotes at start and end of every line and indent properly  ###  i'm sure it's very easy for someone more experienced with a proper editor...  GPT 4 says what I did is a good refactoring BTW..
 I just made it shorter with the 2 functions   also take out my comment that duplicated this MSG at the top.   sorry, I'll get better.

### CODE REVIEW

**Comment by ScottzCodez** [comment]
> @ScottzCodez please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

I don't know how to agree to this, need help

**Comment by ScottzCodez** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by ScottzCodez** [comment]
@microsoft-github-policy-service agree

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by riedgar-ms** [comment]
I think that subsequent changes to the notebook have rendered this obsolete

**Pull request closed without merging**
