### PR TITLE
Use `llguidance` JSON grammar

### PR DESCRIPTION
**Pull request by hudson-ai**
Replaces the JSON grammar implementation with `llguidance`'s rust `JsonCompiler`. To do this, I introduced a new terminal `GrammarFunction` class called `LLGrammar`, which just wraps a serialized `llguidance`-native grammar.

This PR also refactors the __slots__ and overall inheritance structure in _grammar.py a bit in order to align with the `llguidance` API. Notably, max_tokens is only allowed on classes that will serialize to Gen, Lexeme, or GenGrammar, where token_limit is reimplemented by wrapping a grammar in a GenGrammar pre-image (Subgrammar).

### CODE REVIEW

**Comment by hudson-ai** [comment]
@riedgar-ms  some of the error messages from json are sadly a little less transparent now -- it's a bit difficult to navigate the boundary of rust and python errors... I noted some TODOs about this in the JSON tests, but I do not think they are critical to follow up on in this particular PR

**Comment by hudson-ai** [comment]
Please note that test failures here are due to the new macos-14 runner being misspecified

**Review by mmoskal — APPROVED** [review]
Looks great, always a good sign when PR removes 1750 lines!

**Review by riedgar-ms — APPROVED** [review]

**Comment by hudson-ai** [comment]
> Looks great, always a good sign when PR removes 1750 lines!

Yes, they definitely didn't move _elsewhere_ 😆

**Pull request merged**
