### PR TITLE
Update to version 0.0.65 with fix of inline select function and test improvements

### PR DESCRIPTION
**Pull request by Danivilanova**
## Summary
This Pull Request updates the version of the project to 0.0.65 and includes a fix of the inline `select` function. Additionally, it updates dependencies in `setup.py` and makes adjustments to tests.

### `guidance/__init__.py`
- Updated the `__version__` attribute from `0.0.64` to `0.0.65`. (this can be reverted if you want)

### `guidance/library/_select.py`
- Correct the implementation of the inline select function. Previously, the parser.visit function was appending all the options to the @raw_prefix, which caused the sentence provided to the model to be incorrect. As a result, a random option was returned.
- Options are now directly extracted from `block_content` rather than through a visit to the parser.
- Changed the tokenization of `options` to be more efficient, avoiding redundant retokenizations.

### `setup.py`
- Removed a trailing comma from the dependencies list.
- Added new extras_require categories: 
  - `mpt` with dependency `einops`, 
  - `llama` with dependency `sentencepiece`.

### `tests/library/test_select.py`
- Added a new test function test_select_text to ensure that the options in select are not being concatenated.

### `tests/llms/transformers/test_llama.py`
- Updated the path for LLaMA model in the test.

### `tests/utils.py`
- Imported `torch` to check for GPU availability.
- Modified `get_transformers_llm` to conditionally set the device to `"cuda:0"` if a GPU is available, otherwise it remains on the CPU.

### CODE REVIEW

**Review by emrekiciman — COMMENTED** [review]
Thank you for this PR.

The changes to _select look good to me.  I verified that this also fixes #323 and #256 .

I didn't see an existing issue with the test_llama.py.  What problem is this solving?  thanks very much,

**Comment by Danivilanova** [comment]
The idea with test_llama.py is to not have to manually download the model when running the tests

**Review by emrekiciman — APPROVED** [review]
Thank you again, @Danivilanova, for this PR.   We suspect there are still other selector bugs that might need a deeper rewrite, but this is an important fix right now as it addresses a problem many are running into.  Much appreciated

**Comment by xnohat** [comment]
Hi @Danivilanova,

I tested this fix for "select" function and got bug for OpenAI . Maybe error at parser.program.llm.tokenizer not available in OpenAI

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/guidance/_program_executor.py", line 109, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/opt/conda/lib/python3.10/site-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/opt/conda/lib/python3.10/site-packages/guidance/_program_executor.py", line 524, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/opt/conda/lib/python3.10/site-packages/guidance/library/_select.py", line 60, in select
    options_tokens = parser.program.llm.tokenizer([variable_stack["@prefix"] + option for option in options]).input_ids
AttributeError: 'OpenAI' object has no attribute 'tokenizer'

Error in program:  'OpenAI' object has no attribute 'tokenizer'
```
{{#user}}
Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
Sentence: {{example}}
Answer:
{{/user}}
{{~#assistant~}}
{{#select "answer"}} Yes{{or}} No{{or}} Maybe{{/select}}
{{~/assistant~}}

**Comment by riedgar-ms** [comment]
Does this still occur since the refactoring?

**Comment by riedgar-ms** [comment]
I think that subsequent changes to the library have rendered this obsolete?

**Pull request closed without merging**
