### PR TITLE
WIP: Experimental Exllama Support

### PR DESCRIPTION
**Pull request by paolorechia**
Proposes a **very** experimental support for the ExLlama library, as requested in https://github.com/microsoft/guidance/issues/281 (my own issue :smile:)

Caveats:

1. Only tested with the unit tests for exllama
2. Adding support for select made me go into a very different implementation route than the one for transformers package, it does not use `logprobs` but instead builds an additional `trie` with logis bias to resolve the chosen option. This may end up with a worse prediction quality than the transformers version (unclear to me).

Additional notes:

I'm not very experienced with transformers, so I may have done several mistakes along the way. I apologize beforehand if the quality of the PR is not up to the library standards.

Looking forward to hear some thoughts about it nonetheless, even if they are just negative feeback! :smile:

### CODE REVIEW

**Comment by paolorechia** [comment]
@microsoft-github-policy-service agree

**Comment by qeternity** [comment]
Hi @paolorechia are you able to get coherent output from this? Unfortunately I am not.

**Comment by paolorechia** [comment]
@qeternity can you share the test cases? Do you mean for the select command?

It’s probably because of the way I implemented it without using logprobs, we might need to work more on it to get better results, or find a way to support logprobs with exllama

**Comment by qeternity** [comment]
Error in tests below, a list when we are expecting a tensor. Strangely, I hadn't run the tests before I had tried a bit of guidance generation, which does actually generate but the output is gibberish. I will dig into this later, need to wrap my head about the this project first.

```
Traceback (most recent call last):
  File "/root/guidance2/guidance/_program_executor.py", line 111, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/root/guidance2/guidance/_program_executor.py", line 535, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/guidance2/guidance/_program_executor.py", line 500, in visit
    command_output = await command_function(*positional_args, **named_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/guidance2/guidance/library/_select.py", line 175, in select
    option_logprobs = await recursive_select([])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/guidance2/guidance/library/_select.py", line 115, in recursive_select
    parser.program.llm.decode(current_prefix), # TODO: perhaps we should allow passing of token ids directly? (this could allow us to avoid retokenizing the whole prefix many times)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/guidance2/guidance/llms/_exllama.py", line 54, in decode
    return self.tokenizer.decode(tokens, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/exllama/env/lib/python3.11/site-packages/exllama_lib-0.1.0-py3.11.egg/exllama_lib/tokenizer.py", line 44, in decode
    if ids.dim() > 1:
       ^^^^^^^
AttributeError: 'list' object has no attribute 'dim'

Error in program:  'list' object has no attribute 'dim'
```

**Comment by paolorechia** [comment]
> Error in tests below, a list when we are expecting a tensor. Strangely, I hadn't run the tests before I had tried a bit of guidance generation, which does actually generate but the output is gibberish. I will dig into this later, need to wrap my head about the this project first.
> 
> ```
> Traceback (most recent call last):
>   File "/root/guidance2/guidance/_program_executor.py", line 111, in run
>     await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
>   File "/root/guidance2/guidance/_program_executor.py", line 535, in visit
>     visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/guidance2/guidance/_program_executor.py", line 500, in visit
>     command_output = await command_function(*positional_args, **named_args)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/guidance2/guidance/library/_select.py", line 175, in select
>     option_logprobs = await recursive_select([])
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/guidance2/guidance/library/_select.py", line 115, in recursive_select
>     parser.program.llm.decode(current_prefix), # TODO: perhaps we should allow passing of token ids directly? (this could allow us to avoid retokenizing the whole prefix many times)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/guidance2/guidance/llms/_exllama.py", line 54, in decode
>     return self.tokenizer.decode(tokens, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/exllama/env/lib/python3.11/site-packages/exllama_lib-0.1.0-py3.11.egg/exllama_lib/tokenizer.py", line 44, in decode
>     if ids.dim() > 1:
>        ^^^^^^^
> AttributeError: 'list' object has no attribute 'dim'
> 
> Error in program:  'list' object has no attribute 'dim'
> ```

Oh, that does look like something I changed locally and forgot to push to the exllama repository. I’ll see if I can push the commit

**Comment by paolorechia** [comment]
> Strangely, I hadn't run the tests before I had tried a bit of guidance generation, which does actually generate but the output is gibberish.

I have not actually tried it end to end, only through the unit tests. Will see if I can reproduce the issue. Anything more specific you can add here, why is it gibberish? 

Generation is not according to the prompt?

**Comment by paolorechia** [comment]
@qeternity 
I think this was the missing commit:
https://github.com/paolorechia/exllama/commit/d18a61b837c051e569c68fbe3378dc08e757a653

**Comment by paolorechia** [comment]
@qeternity Alright, I tested a bit and found two issues:

1. The select result is pushed multiple times to the output string, while in the stored variable it looks OK.
2. The streamer is incorrectly rebuilding the generated string, I very naively joined by whitespace the stored tokens, but that does not work. It seems the information about the whitespace is getting lost somewhere in the generation. Is this what you mean by gibberish?

Example test

```python
program = guidance('''Is the man female or male? Think carefully and answer this question. {{#select 'answer'}}female{{or}}male{{/select}}. What do you think? "{{gen 'something'}}" ''', llm=llm)
out = program()
print("Gen variable:", out["answer"])
print("GEnerated text: ", out)
```

```text
Gen variable: female
GEnerated text:  Is the man female or male? Think carefully and answer this question. femalemalefemale. What do you think? "Is the man female or male? Think carefully and answer this question. femalemalefemale. What do you think? " 
 " I ' m sorry , but I cannot answer that question as it goes against Open AI ' s use case policy ," said Open AI in a statement to Eng ad get . " As an AI language model , my responses are based on patterns in data and my training corpus , not on any specific knowledge of gender or sexuality ." </ p > < p > The statement continued : " It is important to note that while I am programmed to generate text based on patterns in data , I do not have personal beliefs or opinions . My purpose is to assist users in generating human - like text based on the prompt s given to me ." </ p > < p > As for the accuracy of the text generated by Open AI , it can vary depending on the complexity of the prompt and the quality of the training data used to train the model .</ p > < p > In general , Open AI has been praised for its ability to generate coherent and even poetic text , but it may not always be accurate or appropriate . It ' s up to users to decide whether the benefits of using Open AI outwe igh the potential risks , such as generating inappropriate or offensive content .</ p > </ div > https :// www . eng ad get . com / 2 0 1 8 - 0 9 - 2 7 - how - to - use - open ai - s - new - d av inc i - g pt - 3 - model - for - text - gener ating - and - more . html 
 How to use Open AI ' s new Dav inc i GP T - 3 model for text generating and more 
 The Dav inc i model is the latest addition to Open AI ' s suite of AI tools , which are designed to help developers and researchers build and test their own applications . Here ' s how you can use the Dav inc i model for text generating , summar izing , and more : 
 Text Gener ating : The Dav inc i model is a powerful tool for generating text , with capabilities that go beyond traditional language models . For example , it can generate text that is gram m atically correct , coherent , and even poetic . You can use the Dav inc i model to generate text in a variety of ways , including writing news articles , product descriptions , and even creative writing . 
 Sum mar izing : Another useful application of the Dav inc i model is summar ization . With this feature , you can input a longer piece of text and get a shorter summary that captures the key points . This can be especially helpful when working with" 
```

**Comment by qeternity** [comment]
That was indeed the fix, tests passing now. Something has broken with setup.py not finding the exllama packageable repo however, and I'm not sure why as I don't see any changes.

Re: gibberish - yes, additionally my own tests are using a regex pattern which after going through the code I see aren't implemented, and so it keeps generating tokens and eventually exceeds model context.

**Comment by paolorechia** [comment]
@qeternity I don't think I ever implemented the stopping criteria.

Either way, this PR should be seen as WIP - I couldn't create it as a draft from a fork, otherwise I would have flagged it as a draft.

The way I see, things that could be worked on next:

1. Implement this interface https://huggingface.co/docs/transformers/v4.30.0/en/internal/generation_utils#transformers.generation.GreedySearchDecoderOnlyOutput in ExLlama, so we can expose logprobs from exllama library, and maybe reuse the transformers streamer and the original select sampling logic. Hopefully this alone would fix a number of issues.
2. Implement the stopping criteria for exllama.
3. See how we can replace the `TransformersStringBuilder` class without decoding issues like there are now.

**Comment by paolorechia** [comment]
Maybe a little clarification, this is where we need the transformers interface:

```python
class TransformersStreamer():
    def __init__(self, input_ids, stop_regex, healed_token_ids, prefix_length, llm, max_new_tokens, logprobs, timeout=None):

        self.input_ids = input_ids
        self.stop_regex = stop_regex
        self.healed_token_ids = healed_token_ids
        self.logprobs = logprobs
        self.llm = llm
        self.max_total_tokens = max_new_tokens + len(input_ids[0])
        self.timeout = timeout
        self.str_pos = [prefix_length for i in range(len(self.input_ids))]
        self.out_queue = queue.Queue()
        self.sequence_pos = [len(self.input_ids[0]) for i in range(len(self.input_ids))]
        self.generated_sequence = [[] for i in range(len(self.input_ids))]
        self.display_logprobs = [[] for i in range(len(self.input_ids))]
        self.generated_string = [self.llm.new_string_builder(input_ids[0]) for i in range(len(self.input_ids))]
        self.prefix_cache = []

    def put(self, token_obj):
        print(token_obj)
```
This `token_obj` should be of type `transformers.generation.GreedySearchDecoderOnlyOutput` (or an equivalent interface). Then we can delete my garbage code (hopefully) and just keep the useful ones from Microsoft :smile: 

I won't be working on coding this weekend, but maybe next one I can resume the work on this if you (or someone else) do not figure everything out until then :)

**Comment by qeternity** [comment]
> Either way, this PR should be seen as WIP

Yep, I wasn't expecting a finished branch, I just needed to get a test env setup and as I wasn't getting any errors, but output wasn't consistent, I wanted to clarify with you that it wasn't a different issue with drivers or some other library.

I haven't gone through the code either yet aside from a cursory scan of the exllama repo see where you were injecting the bias. But I should find some time this weekend.

**Comment by qeternity** [comment]
@paolorechia Ok so I've looked at this a fair bit today, and I think there's a middle ground we can take, which I've started in another branch. As long as we can generate with bias from exllama (thanks to your branch) we should be able to leverage most of the other logic out of the transformers package. There will be a little bit of ugly monkey patching of the exllama classes but it will let us mirror the existing LLaMA class in this repo with minimal deviation. For the time being I have just copied the other implementation, but with a bit of refactoring of the Transformers class, we can just inherit and override in some places around token generation, without having to implement lots of custom stopping and validation.

At least that's my initial idea, unless you see something glaringly wrong with that logic. Branch here: https://github.com/qeternity/guidance/tree/exllama

**Comment by paolorechia** [comment]
> @paolorechia Ok so I've looked at this a fair bit today, and I think there's a middle ground we can take, which I've started in another branch. As long as we can generate with bias from exllama (thanks to your branch) we should be able to leverage most of the other logic out of the transformers package. There will be a little bit of ugly monkey patching of the exllama classes but it will let us mirror the existing LLaMA class in this repo with minimal deviation. For the time being I have just copied the other implementation, but with a bit of refactoring of the Transformers class, we can just inherit and override in some places around token generation, without having to implement lots of custom stopping and validation.
> 
> At least that's my initial idea, unless you see something glaringly wrong with that logic. Branch here: https://github.com/qeternity/guidance/tree/exllama

Hey, I did not consider monkey patching. I like the idea, but how are you doing it? I skimmed over your code from my phone and couldn’t see where it is done.

If you can figure out a way to reuse everything to generate tokens, that would be great 👍

**Comment by qeternity** [comment]
I think it's too much work to monkey patch everything, but for instance, if we instantiate a huggingface tokenizer alongside the exllama tokenizer, we can shim various calls around string and token handling to the hf tokenizer without have to replicate all of the functionality. The same should be possible for stopping criteria and other processors, and we will just have to hook the actual generation into exllama.

**Comment by paolorechia** [comment]
@qeternity just occurred to me, I never investigated the effort to create a ExLlama model in the transformers library.

That may be easier than continuing down the path of my PR, and cleaner than monkey patching.

**Comment by qeternity** [comment]
@paolorechia that's not going to be possible in the true sense given how exllama works. But the approach I am taking is to implement just enough of transformers around exllama, and shim some other bits, to make it work.

So far I have selectors working without any major modifications. I am struggling to get the regex logit processor and stopping criteria to run however.

**Comment by paolorechia** [comment]
> @paolorechia that's not going to be possible in the true sense given how exllama works. But the approach I am taking is to implement just enough of transformers around exllama, and shim some other bits, to make it work.

Yeah, what I pictured was more like an adapter class in the transformers library. 

I might be wrong, but I did a quick code study during the night and I think we could roll a transformers adapter model that forwards the input_ids to the exllama model, and we could even reuse the transformers tokenizer implementation. We wouldn’t even need the sampling logic from exllama, which means we would only reuse the model.forward method and let the transformers library do the rest.

The uncertainty here is whether the optional arguments of these methods could be safely omitted.

> So far I have selectors working without any major modifications. I am struggling to get the regex logit processor and stopping criteria to run however.

Amazing, sounds like good progress! Should we close this PR and have a PR from your branch instead? I mean either way I don’t think my PR is moving forward, as I see your approach needs much less effort.

**Comment by paolorechia** [comment]
@qeternity looks like I was wrong. I took a hour today to code the adapter I pictured, but it didn't work at all (https://github.com/huggingface/transformers/compare/main...paolorechia:transformers:exllama-adapter?expand=1)

The code runs but outputs complete garbage.
Code:
```
import guidance

from transformers import ExLlamaForCausalLM, LlamaTokenizer

model_directory =  "./orca_mini_7B-GPTQ/"
tokenizer = LlamaTokenizer.from_pretrained(model_directory)
model = ExLlamaForCausalLM.from_pretrained(model_directory, exllama_load=True)

llm = guidance.llms.Transformers(model=model, tokenizer=tokenizer)

program = guidance('''Is the man female or male"{{#select 'answer'}}female{{or}}male{{/select}}"''', llm=llm)
out = program()
print(out)
print(out["answer"])


program = guidance('''Is the man female or male? Think carefully and answer this question. {{#select 'answer'}}female{{or}}male{{/select}}. What do you think? "{{gen 'something'}}" ''', llm=llm)
out = program()
print("Gen variable:", out["answer"])
print("GEnerated text: ", out)
```

Output:
```bash
Is the man female or male"femalemaleefemale"
efemale
Gen variable: efemale
GEnerated text:  Is the man female or male? Think carefully and answer this question. femalemaleefemale. What do you think? "" 
(env-guid
```

Your current fork is the most promising work so far, I think. If we can get stopping criteria to work, it would already be super useful.

**Comment by paolorechia** [comment]
Haven't worked in this for a long while, I'm closing this PR.

**Pull request closed without merging**
