### PR TITLE
Add support for Llama2, Palm, Cohere, Replicate, Hugging Face Models - using litellm 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

Here's a sample of how it's used:

```python
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call - async completion
response = acompletion(model="gpt-3.5-turbo", messages=messages)

# llama2 call
model_name = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
response = completion(model_name, messages)

# cohere call
response = acompletion("command-nightly", messages)

# anthropic call
response = acompletion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Can I get a review on this PR @slundberg @Harsha-Nori 😊? If this initial commit looks good happy to add any additional tests / docs

**Review by emrekiciman — COMMENTED** [review]
Thank you for this PR.  Being able to use OpenAI, Azure, Cohere, Anthropic, Huggingface API endpoints via the same code would be great.

@Harsha-Nori or @slundberg may have different thoughts, but let me ask about a couple of items on my mind:

1. Guidance supports some model specific behaviors (e.g., different formats or roles chat via json or special tokens).  Have you checked whether litellm interacts with that?  With this PR, would guidance just pretend it's using an openai model and have litellm translate these model-specific behaviors?

2. You show an example of llama2 in your conversation post.  Is this code change to use acompletion() within _openai.py also providing support for local models?  That would interact with (i.e., probably disable) some of Guidance's acceleration features, and this would be something to be careful and clear about. 

3. It's not clear to me that this belongs in the class _openai.py, if only from a naming perspective.  Maybe it would be better to have a first PR that makes a new separate class, e.g., guidance/llms/_litellm.py ?

4. Like you already mention, documentation and tests would be important.

Thanks again for this PR.  It would be really nice to broaden the set of REST endpoints that are easy to use from Guidance.

**Comment by krrishdholakia** [comment]
Hey @emrekiciman i'll work with @ishaan-jaff to ensure we support any model specific work y'all do. We also actively invest in making sure we map to the model specific prompt templates, etc. - so if there's any we're missing (e.g. vicuna), will make the necessary changes. 

Thanks for the feedback. We've been fans of guidance since launch https://github.com/guidance-ai/guidance/issues/133

**Comment by fjfricke** [comment]
how did you get the correct tokenizer working? Getting an error from tiktoken that the correct tokenizer could not be mapped.

**Comment by krrishdholakia** [comment]
hey @fjfricke could you tell me more about the error? is this when using litellm or in general?

**Comment by fjfricke** [comment]
> hey @fjfricke could you tell me more about the error? is this when using litellm or in general?

When I am using guidance with litellm and a non-gpt model (like llama2), tiktoken doesn't work because the model provided is not in its list of encodings. It only happens when using litellm and a non-gpt model.

**Comment by ishaan-jaff** [comment]
> Guidance supports some model specific behaviors (e.g., different formats or roles chat via json or special tokens). Have you checked whether litellm interacts with that? With this PR, would guidance just pretend it's using an openai model and have litellm translate these model-specific behaviors?

-> litellm only translates the input. Example max_tokens -> get converted to max_tokens. Did that answer this question ? 

> You show an example of llama2 in your conversation post. Is this code change to use acompletion() within _openai.py also providing support for local models? That would interact with (i.e., probably disable) some of Guidance's acceleration features, and this would be something to be careful and clear about.

-> as for local models we have an ollama integration https://github.com/jmorganca/ollama

> It's not clear to me that this belongs in the class _openai.py, if only from a naming perspective. Maybe it would be better to have a first PR that makes a new separate class, e.g., guidance/llms/_litellm.py ?

-> will add litellm in a separate file

Like you already mention, documentation and tests would be important

**Comment by ishaan-jaff** [comment]
@emrekiciman updated this based on feedback, created a _litellm.py

**Comment by yihanaira** [comment]
> > hey @fjfricke could you tell me more about the error? is this when using litellm or in general?
> 
> When I am using guidance with litellm and a non-gpt model (like llama2), tiktoken doesn't work because the model provided is not in its list of encodings. It only happens when using litellm and a non-gpt model.

I am facing the same issue. Could @krrishdholakia and @ishaan-jaff provide some example of using non-OpenAI model with your branch.
I am trying to use like: guidance.llms.LiteLLM(model="bedrock/anthropic.claude-v2", encoding_name="cl100k_base"), but get similar issue as @fjfricke did.

**Comment by waywardspooky** [comment]
Guidance compatibility with litellm is greatly needed. The ability to plug in a replacement for openai server/model opens up the use/implementation of this project for a much wider user base.

**Comment by slundberg** [comment]
Hi all. Inspired by this PR and others we added Lite LLM support for the new v0.1x releases. If you have any issues with that implementation speak up. For now I am closing this PR.

**Pull request closed without merging**
