### PR TITLE
Update protobuf definitions for remote list_append fix

### PR DESCRIPTION
**Pull request by nking-1**
Fix for the issue https://github.com/guidance-ai/guidance/issues/920. The issue is that the `list_append` feature in `gen` does not work with remote models.

The primary fix here was to update protobuf definitions to support lists inside the captured values. When I generated code from the new protobuf definitions, it resulted in Protobuf automatically using a new version. The old version is `4.25.2` and the new one is `5.27.1`. I'm not sure if that is much of a problem or not.

### CODE REVIEW

**Comment by hudson-ai** [comment]
Thanks for working on this @nking-1!
With the big caveat that I don't know much about protobuf... this looks reasonable so long as that test is passing :)

@riedgar-ms @paulbkoch @Harsha-Nori can any of you comment? I'm particularly wondering if there is any way to make the serialization/deserialization a bit more "automated" since I'd expect union types to be pretty common use cases?

**Comment by hudson-ai** [comment]
@riedgar-ms great idea, but would you consider that required for approval, or can it go on the backlog?

**Comment by riedgar-ms** [comment]
I'd be happy for a fast-follow. The added test at least flexed the new addition.

**Comment by hudson-ai** [comment]
@nking-1 this should hopefully pass the gates after #936 is merged. Approved from me and will (conditionally) merge unless anyone objects :)

**Comment by nking-1** [comment]
Richard raised some concerns about potential backwards compatibility. Let's wait for Michal's review before merging this.

I agree that protobuf-specific tests are important. I can work on that as a followup task.

**Comment by hudson-ai** [comment]
Got it. @mmoskal could you take a look when you get a chance?

**Comment by mmoskal** [comment]
is there protobuf used to anything other than the azure_guidance? (which we are replacing with JSON)

**Comment by hudson-ai** [comment]
@mmoskal just to make a distinction -- there are two protobuf models (protocols?) we are currently using:
1. `GrammarFunction`
   - Currently used by `AzureGuidance` and "local" guidance servers (pretty sure that's it)
   - Aim should be to replace both with the JSON version eventually
2. `EngineCallResponse`
   - The main focus of this PR
   - Currently used only by "local" guidance servers (`AzureGuidance` is currently a bit nasty and is more manually parsed from JSON embedded in logs -- would be good to standardize on a specific JSON response model from the API and use in both situations?)

**Comment by mmoskal** [comment]
I see. A common JSON format for response sounds like a good idea!

Given that all this data is processed in Python anyways, I don't think protobuf gives us much of a performance advantage over JSON, especially if we use `ujson` package or similar.

**Comment by hudson-ai** [comment]
I think I agree. In the meantime, I don't think there should be any backwards compatibility issues wrt AzureGuidance (I expect that was the primary concern?) as we are changing that whole thing out anyway. @mmoskal do you agree? If so I think we should merge this in the meantime and I can work on replacing protobuf entirely on our feature branch

**Comment by mmoskal** [comment]
@hudson-ai yes, agreed!

**Pull request merged**
